name: Build and run docker compose

on:
  push:
  pull_request:

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start containers
      run: |
        docker compose pull
        make initialize_docker
        docker compose up -d

    - name: Extract Locales
      run: |
        make extract_locales

    - name: Set environment variable "commit-message"
      run: echo "commit-message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
    - name: Set environment variable "commit-author"
      run: echo "commit-author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV

    - name: Push Locales
      run: |
        git config --global user.name "${{ env.commit-author }}"
        git config --global user.email "username@users.noreply.github.com"
        git checkout -b test-locales
        git commit -a -m "${{ env.commit-message }}"
        git push -u origin test-locales

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
